version: '3'
services:
  myapplication:
    image: mongodb/mongodb-community-server:8.0-ubi8
    environment:
      - CONN_STR=mongodb://user:pass@mongodb:27017/admin
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db